[package]
name = "watch-n-paint"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
image = "0.25.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
uuid = { version = "1.11.1", features = ["v4"] }
